# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production_kittygram:
  static_volume_kittygram:

# Всё отличие — заменяем build на image и указываем, какой образ использовать.
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production_kittygram:/var/lib/postgresql/data
  backend:
    image: radziukdzmitry/kittygram_backend
    env_file: .env
    volumes:
      - static_volume_kittygram:/backend_static
  frontend:
    image: radziukdzmitry/kittygram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_kittygram:/frontend_static
  gateway:
    image: radziukdzmitry/taski_gateway  # Качаем с Docker Hub.
    env_file: .env
    volumes:
      - static_volume_kittygram:/staticfiles/
    ports:
      - 9000:80 